#!/bin/zsh
# Configure with CMake and build.
set -euo pipefail
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B build "$@" \
    && cmake --build build
# Symlink compile_commands.json to the project root for clangd / LSPs.
ln -sf build/compile_commands.json .
